// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkM-kuAb0lx7-OFEUbRBzqBmT2NkI8IAM',
    appId: '1:510183756171:web:8e88b7b273f2fa70779f8e',
    messagingSenderId: '510183756171',
    projectId: 'mobx-reminder-7ac60',
    authDomain: 'mobx-reminder-7ac60.firebaseapp.com',
    storageBucket: 'mobx-reminder-7ac60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKyY_Q9tzgVHDJB2l0618e7vLVlFwikRw',
    appId: '1:510183756171:android:f6e68011c3711907779f8e',
    messagingSenderId: '510183756171',
    projectId: 'mobx-reminder-7ac60',
    storageBucket: 'mobx-reminder-7ac60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhgXmVOMxoKMtzmnNT2bPgdyWI0WvkW0Y',
    appId: '1:510183756171:ios:5d2cbf76866b98fd779f8e',
    messagingSenderId: '510183756171',
    projectId: 'mobx-reminder-7ac60',
    storageBucket: 'mobx-reminder-7ac60.appspot.com',
    iosBundleId: 'com.example.mobxReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhgXmVOMxoKMtzmnNT2bPgdyWI0WvkW0Y',
    appId: '1:510183756171:ios:040666c3af5fb1fd779f8e',
    messagingSenderId: '510183756171',
    projectId: 'mobx-reminder-7ac60',
    storageBucket: 'mobx-reminder-7ac60.appspot.com',
    iosBundleId: 'com.example.mobxReminder.RunnerTests',
  );
}
